version: '3.7'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack_service
    ports:
      - '4566:4566'
    environment:
      - DATA_DIR=/tmp/localstack/data
      - SERVICES=s3
    volumes:
      - ./volume:/tmp/localstack
      - ./sh:/etc/localstack/init/ready.d
      
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
